USE [master]
GO

/****** Object:  Database [CalculadoraSQIA]    Script Date: 09/06/2025 21:50:59 ******/
CREATE DATABASE [CalculadoraSQIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CalculadoraSQIA', FILENAME = N'/var/opt/mssql/data/CalculadoraSQIA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CalculadoraSQIA_log', FILENAME = N'/var/opt/mssql/data/CalculadoraSQIA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CalculadoraSQIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CalculadoraSQIA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET ARITHABORT OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CalculadoraSQIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CalculadoraSQIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CalculadoraSQIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CalculadoraSQIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET RECOVERY FULL 
GO

ALTER DATABASE [CalculadoraSQIA] SET  MULTI_USER 
GO

ALTER DATABASE [CalculadoraSQIA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CalculadoraSQIA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CalculadoraSQIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CalculadoraSQIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CalculadoraSQIA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CalculadoraSQIA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CalculadoraSQIA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CalculadoraSQIA] SET  READ_WRITE 
GO


